language: python
env: # These should match the tox env list
    - TOXENV=py26
    - TOXENV=py27
    - TOXENV=py33
    - TOXENV=py34
    - TOXENV=pypy
install: pip install coveralls tox --use-mirrors
script: tox
after_success:
    - coveralls
